# Replace [absolute_path] with your repository path.
policies:
  - executable: "filepath = [absolute_path]/agent/example/accessor/accessor"
    can_access_dirs:
      - "[absolute_path]/agent/example/protected:read"

attributes:
  - path: "type = executable | filepath = /usr/local/bin/my-bpf-tool"
    allowed_bpf_ops: true

flags:
  security_level: "sandbox"
  disable_bpf_ops: true
  enable_openat: false
  secure_maps: true
