# Replace [absolute_path] with your repository path.
policies:
  - executable: "filepath = [absolute_path]/agent/example/accessor/accessor"
    can_access_dirs:
      - "[absolute_path]/agent/example/protected:read"

flags:
  security_level: "sandbox"
